### ISSUE TITLE
'R for Data Science' links to old edition

### ISSUE THREAD

**Issue by tesaunders** [AtlasOfLivingAustralia/cleaning_data#41]
Link to 'R for Data Science' in the [introduction section](https://cleaning-data-r.ala.org.au/introduction.html#r) goes to [first edition](https://r4ds.had.co.nz/index.html), but there is a [newer edition](https://r4ds.hadley.nz/).

**Comment by daxkellie** [comment]
Great pick up, thanks! This will be updated on the next minor update 😃
